### ISSUE TITLE
%player% placeholder not working.

### ISSUE THREAD

**Issue by download042** [St3venAU/ArmorStandTools#16]

**Comment by download042** [comment]
![image](https://user-images.githubusercontent.com/13710574/47785620-8922bf00-dd09-11e8-9383-b67fe5a87f3f.png)

AST: v.2.3.5
Spigot 1.11.2

**Comment by St3venAU** [comment]
Unfortunately the placeholder feature was only added in AST v3.0.0, so is not available in v2.4.3.
