### ISSUE TITLE
WorldGuard exclude regions

### ISSUE THREAD

**Issue by baticag** [St3venAU/ArmorStandTools#20]
I am using PlotSquared and WorldGuard with your plugin on a server.
The problem is that we have Plots where all players are marked as Trusted/Added so they can place ArmorStands in them.

It would be great if we have a WorldGuard flag or config list of regions that ArmorStandTools will not work in.

Thank you in advance!

**Comment by baticag** [comment]
Any news about this problem?

**Comment by St3venAU** [comment]
I have implemented a custom worldguard flag, but I have not had a change to test it fully as I have been super busy. If you want I could send you a development build and you could give me your feedback?

**Comment by baticag** [comment]
Sure, email is batica@serb-craft.com
