### ISSUE TITLE
WorldGuard disable interaction.

### ISSUE THREAD

**Issue by astetyn** [St3venAU/ArmorStandTools#23]
Hello.

Using 1.12.2 with versions AST 2.4.3. World Guard 6.2.2.

I have enabled in my regions flags interaction and use, but player still cant click on armor stand to execute cmd binded on that armor stand. It just write "You cant change that here." Is it issue with integration with WorldGuard? Or whats the flag for enable this?

**Comment by FilipeeX** [comment]
Hi @astetyn, can you please tell me how exactly did you fix it? I'm having the same issue right now and i can't find any flag that corresponds to the permission of clicking an armor stand (or changing its gear as world guard likes to refer to it).
Thanks.
