### ISSUE TITLE
PlotSquared Api Update needed

### ISSUE THREAD

**Issue by Aurelien30000** [St3venAU/ArmorStandTools#32]
With recent and premium version of PlotSquared (v5), link is broken, could you fix it ? Thanks :)

**Involved stacktrace :**
`>.... [10:27:34 WARN]: java.lang.NoClassDefFoundError: com/github/intellectualsites/plotsquared/api/PlotAPI
>.... [10:27:34 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.PlotSquaredHook.<init>(PlotSquaredHook.java:19)
>.... [10:27:34 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.Config.reloadMainConfig(Config.java:177)
>.... [10:27:34 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.Config.reload(Config.java:66)
>.... [10:27:34 WARN]: at com.gmail.St3venAU.plugins.ArmorStandTools.Main.onEnable(Main.java:68)
>.... [10:27:34 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
>.... [10:27:34 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
>.... [10:27:34 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
>.... [10:27:34 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471)
>.... [10:27:34 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385)
>.... [10:27:34 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
>.... [10:27:34 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
>.... [10:27:34 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895)
>.... [10:27:34 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [10:27:34 WARN]: Caused by: java.lang.ClassNotFoundException: com.github.intellectualsites.plotsquared.api.PlotAPI
>.... [10:27:34 WARN]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
>.... [10:27:34 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
>.... [10:27:34 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
>.... [10:27:34 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>.... [10:27:34 WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>.... [10:27:34 WARN]: ... 14 more
>.... [10:27:34 WARN]: [ArmorStandTools] PlotSquared plugin was found, but there was an error initializing PlotSquared support.`

**Comment by xion87** [comment]
can you do it?

**Comment by Aurelien30000** [comment]
@xion87 try this https://github.com/Aurelien30000/ArmorStandTools/actions/runs/159858997 :D
