### ISSUE TITLE
1.16 support

### ISSUE THREAD

**Issue by Aurelien30000** [St3venAU/ArmorStandTools#34]
Hey !

Just a small issue to inform you that your plugin needs an update to fully support 1.16 version of MineCraft. Issues are caused by NMS changes.

Thanks :)

**Comment by Aurelien30000** [comment]
For interested people, try this https://github.com/Aurelien30000/ArmorStandTools/actions/runs/159858997 :D 
Also includes new PlotSquared API and Material fix (thanks to @pollitoyeye)
Now only works in 1.15+!

**Comment by jackstrosahl** [comment]
@Aurelien30000 PR these changes?  Although it seems they aren't being accepted.

**Comment by Aurelien30000** [comment]
> @Aurelien30000 PR these changes? Although it seems they aren't being accepted.

I'll propose a PR if the author "comes back".

**Comment by stijnb1234** [comment]
Done :)
