### ISSUE TITLE
DB Support (MySQL, MongoDB...)

### ISSUE THREAD

**Issue by x9nico** [St3venAU/ArmorStandTools#36]
Hi, is it possible to add support for DB for network servers please ?

Because I want to sync across-servers all my armor stands on my maps ? :)

**Comment by MrKorvic** [comment]
As far as I've seen this isn't doable as there is no data file other than the world itself. All the plugin is doing is summoning an armour stand entity then allowing you to live-edit its values. If you need your worlds to be sync'd for this you could always copy across servers with a cron-job (i.e. if you're running an RPG/MMO setup), but ASTools won't be able to do that for you, unfortunately.
