### ISSUE TITLE
Can't move armorstand in negative direction with crouchRightClickOpensGUI

### ISSUE THREAD

**Issue by Toseflo** [St3venAU/ArmorStandTools#58]
When you have crouchRightClickOpensGUI enabled in the config, you can't move an amorstand in a negative direction anymore. You have to crouch + right click with the shears to move an armorstand in the negative x/y/z direction. But this now opens the GUI rather than moving the armorstand.

Also since I don't know how well comments are visible in closed issues, it would be nice if you could look at this suggestion ^^ https://github.com/St3venAU/ArmorStandTools/issues/53#issuecomment-942433624

**Comment by Aurelien30000** [comment]
Fixed here, opening gui is now ignored using a tool. If you need a fix in the moment, download my fork here: https://github.com/Aurelien30000/ArmorStandTools/actions/runs/1455046170

**Comment by Toseflo** [comment]
Fixed in 4.4.0
