### ISSUE TITLE
Can't move armor stands since 2.04 - teleported back

### ISSUE THREAD

**Issue by divad** [St3venAU/ArmorStandTools#6]
Hi,

As reported in a review on the plugin page:

"When I downloaded the latest version, when I tried to place an armor stand it kept teleporting to me, or teleporting me to it, even though I was just trying to move around. I had to download the version prior to 2.04 to get it to work, please fix."

I can confirm this is also affecting my server on Spigot 1.8. You can no longer move around with an armor stand as you keep being pulled back to the same spot.

**Comment by St3venAU** [comment]
Fixed
