### ISSUE TITLE
Dupe glitch with offhand and /hat

### ISSUE THREAD

**Issue by Kolterdyx** [St3venAU/ArmorStandTools#61]
When Essentials and ASTools are both installed, the player can do /ast to enter armor stand editing mode, then do /hat with any of the items (most likely the nether star for the GUI tool), and then do /ast again to recover their inventory. After that, the GUI tool (or any other item from the ast kit that was used with /hat) will appear in the player's inventory, and they will be able to use it without problems. The same can be achieved by putting the item in the offhand

Suggestions to fix the problem:
 - Allow changing the items of the kit in the config.
 - Look for kit items in the player's armor slots

**Comment by Aurelien30000** [comment]
You may consider using ``essentials.hat.prevent-type.x`` permission, honestly nothing can be done on AST side, except allowing to change items.

**Comment by Kolterdyx** [comment]
> 
> 
> You may consider using `essentials.hat.prevent-type.x` permission, honestly nothing can be done on AST side, except allowing to change items.

That's what I have done, but players can still dupe nether stars with their offhand, which doesn't have a permission node. I'm going to modify the code of the plugin to change the items in my server, but I'd suggest adding a config for them.

**Comment by St3venAU** [comment]
You should be able to prevent this by adding the following to ArmorStandTools' config.yml:
`deniedCommandsWhileUsingTools:
  - hat`
