### ISSUE TITLE
"Pick Up As Item"-Tool doesn't remove armorstand in survival mode anymore

### ISSUE THREAD

**Issue by Toseflo** [St3venAU/ArmorStandTools#65]
In version 4.3.0 when you added the new Pick Up As Item Tool, the tool removed the armorstand when you were in survival mode to prevent duping. 
In version 4.4.1, the armorstand doesn't disappear when using the tool in survival mode, which enabled a very easy dupe for players.

**Comment by St3venAU** [comment]
Thanks for pointing this out. Fixed in 4.4.2 just released.
