### ISSUE TITLE
Wrong plugin version at SpigotMC (4.4.2)

### ISSUE THREAD

**Issue by Dymeth** [St3venAU/ArmorStandTools#70]
When downloading the plugin from SpigotMC, version 4.4.2 is loaded, although version 4.4.3 is specified in the description.
This leads to incorrect work of plugins that check all plugins for updates. 
![image](https://user-images.githubusercontent.com/21080646/149651730-a142c0c9-cb26-411d-9dcb-f96d3a529036.png)

**Comment by St3venAU** [comment]
Thanks. Fixed.
