### ISSUE TITLE
The translate in Spanish | Copy / Paste

### ISSUE THREAD

**Issue by cetub333** [St3venAU/ArmorStandTools#74]
[Traducción.txt](https://github.com/St3venAU/ArmorStandTools/files/8583212/Traduccion.txt)
# Armor Stand Tools
# by St3venAU
# St3venAU@gmail.com
#
# Language Config
#
# File generated by: v4.4.4
# (If this is not the version you are running, consider deleting this
#  config to allow it to be re-created. There may be new config options)
#
# If you are looking for a translated version of this file, check here:
# https://www.spigotmc.org/resources/armor-stand-tools.2237/
#
# Edit these strings if you wish to customize the wording
# or the language of the text used in this plugin.
#
# IMPORTANT: Only edit the text that is between the single
# quotation marks: 'like this'
# If you change anything outside of the quotation marks,
# errors will occur.
# Do not use ' marks inside the string itself.
#
# If you ever wish to return to the default language config,
# delete this file and reload the plugin. A new default language
# file will be generated.
#
####################
# General Messages #
####################
invReturned: 'Contenido del inventario devuelto'
asDropped: 'Soporte de armadura caído'
asVisible: 'Visible'
isTrue: 'Verdadero'
isFalse: 'Falso'
carrying: 'Has cogido el Soporte de armadura. Haga clic para soltar.'
generalNoPerm: 'Sin permiso para esta herramienta y/o región'
cbCreated: 'Bloque de comando creado'
size: 'Tamaño'
small: 'Pequeño'
normal: 'Normal'
basePlate: 'Placa base'
isOn: 'On'
isOff: 'Off'
gravity: 'Gravedad'
arms: 'Brazos'
invul: 'Invulnerable'
equip: 'Equipamiento'
locked: 'Bloqueado'
unLocked: 'Desbloqueado'
currently: 'Actualmente'
notConsole: 'Este comando no se puede ejecutar desde la consola'
giveMsg1: 'Dadas las herramientas del soporte de armadura. Haga clic izquierdo en cualquier herramienta para recorrerlas.'
giveMsg2: 'Ejecute este comando nuevamente para devolver su inventario.'
conReload: 'Configuración de Armor Stand Tools recargada'
noRelPerm: 'No tienes permiso para recargar este plugin'
invalidName: 'No es un nombre de usuario de Minecraft válido'
wgNoPerm: 'No hay permiso para alterar un soporte de armadura en esta región'
noCommandPerm: 'No tienes permiso para usar este comando'
armorStand: 'Soporte de armadura'
none: 'Ninguno'
guiInUse: 'La GUI de esta armadura está en uso'
# New since v2.4.0:
noASNearBy: 'No se encontró ningún soporte de armadura cerca'
closestAS: 'Soporte de armadura más cercano'
type: 'Tipo'
command: 'Comando'
# New since v3.2.0
creativeRequired: 'Se requiere el modo creativo para guardar un soporte de armadura como un bloque de comando'
# New since v3.3.0
cmdOnCooldown: 'Este comando está en enfriamiento'
cooldownRemovedFrom: 'Enfriamiento eliminado de'
isAnInvalidCooldown: 'es un tiempo de enfriamiento inválido'
cooldownSetTo: 'Enfriamiento establecido en'
ticksFor: 'ticks por'
setCooldown: 'Establecer el tiempo de reutilización para el comando'
removeCooldown: 'Eliminar el enfriamiento del comando'
# New since v3.4.1
glow: 'resplandor'
cmdNotAllowed: 'Ese comando no está permitido mientras se usan las herramientas de Armor Stand'
#New since v4.0.0
crouch: 'agacharse'
click: 'Click'
finish: 'Finalizar'
#New since v4.3.0
configuredArmorStand: 'Soporte de armadura configurado'
name: 'Nombre'
inventory: 'Inventario'
items: 'Items'
stacks: 'Stacks'
invisible: 'Invisible'
invuln: 'Invulnerable'
glowing: 'Resplandeciente'
attributes: 'Atributos'
hasTheseCmdsAssigned: 'tiene estos comandos asignados'
hasNoCmds: 'no tiene comandos asignados'
priority: 'Prioridad'
delay: 'Retraso'
errorExecutingCmd: 'Ocurrió un error al ejecutar el comando'
isNotValidNumber: 'no es un número válido'
removedFromAs: 'eliminado del soporte de la armadura'
listAssignedCmds: 'Lista de comandos asignados'
addACmd: 'Agregar un comando'
removeACmd: 'Eliminar un comando'
cmdHelp: 'Este comando se usa para agregar/eliminar comandos al soporte de armadura más cercano (dentro de 4 bloques). Los comandos se ejecutan cuando se hace clic derecho en el soporte de la armadura, primero la prioridad más baja.'
#New since v4.4.0
enterName: 'Ingrese el nombre del soporte de la armadura en el chat'
enterName2: 'Ingrese el nombre del soporte de la armadura en el chat, o para eliminar el nombre, ingrese:'
enterSkull: 'Ingrese el nombre de usuario para la cabeza del soporte de la armadura en el chat'
inputTimeout: 'Tiempo de espera de entrada. Inténtalo de nuevo.'
nameSet: 'Seleccionado nombre de soporte de armadura'
nameRemoved: 'Nombre de soporte de armadura eliminado'
skullSet: 'Seleccionada cabeza con soporte de armadura.'
#New since v4.4.1
enterNameC: 'Para configurar el nombre del soporte de la armadura'
enterNameC2: 'O para quitar el nombre'
enterSkullC: 'Para configurar el nombre de usuario de MC para la cabeza'
#############################
# Tool names & descriptions #
#############################
tool:
  summon:
    name: 'Soporte de armadura'
    lore:
      - 'Click derecho para invocar un soporte de armadura y recogerlo'
      - 'Cualquier clic lo soltará'
  gui:
    name: 'Guía multiherramientas'
    lore:
      - 'Click derecho para abrir una GUI para modificar el Soporte de armadura.'
      - 'los atributos de la armadura se mantienen o cambian'
      - 'su armadura y artículos'
  rotat:
    name: 'Rotación'
    lore:
      - 'Click derecho en el para cambiar su rotación Soporte de armadura'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  headX:
    name: 'Cabeza X'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la cabeza X'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  headY:
    name: 'Cabeza Y'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Cabeza Y'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  headZ:
    name: 'Cabeza Z'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Cabeza Z'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  lArmX:
    name: 'Brazo izquierdo X'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Brazo izquierdo X'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  lArmY:
    name: 'Brazo izquierdo Y'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Brazo izquierdo Y'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  lArmZ:
    name: 'Brazo izquierdo Z'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Brazo izquierdo Z'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  rArmX:
    name: 'Brazo derecho X'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Brazo derecho X'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  rArmY:
    name: 'Brazo derecho Y'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Brazo derecho Y'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  rArmZ:
    name: 'Brazo derecho Z'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Brazo derecho Z'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  moveX:
    name: 'Movimiento X'
    lore:
      - 'Click derecho armor para mover +0.1 X'
      - 'Shift + Click derecho para -0.1 X'
  moveY:
    name: 'Movimiento Y'
    lore:
      - 'Click derecho armor para mover +0.1 Y'
      - 'Shift + Click derecho para -0.1 Y'
  moveZ:
    name: 'Movimiento Z'
    lore:
      - 'Click derecho armor para mover +0.1 Z'
      - 'Shift + Click derecho para -0.1 Z'
  lLegX:
    name: 'Pierna izquierda X'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Pierna izquierda X'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  lLegY:
    name: 'Pierna izquierda Y'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Pierna izquierda Y'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  lLegZ:
    name: 'Pierna izquierda Z'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Pierna izquierda Z'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  rLegX:
    name: 'Pierna derecha X'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Pierna derecha X'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  rLegY:
    name: 'Pierna derecha Y'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Pierna derecha Y'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  rLegZ:
    name: 'Pierna derecha Z'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Pierna derecha Z'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  bodyX:
    name: 'Cuerpo X'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Cuerpo X'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  bodyY:
    name: 'Cuerpo Y'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Cuerpo Y'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  bodyZ:
    name: 'Cuerpo Z'
    lore:
      - 'Click derecho en el Soporte de armadura para cambiar el valor de la Cuerpo Z'
      - 'El valor depende de qué tan alto haga clic en el cuerpo'
  gui_move:
    name: 'Recoger (Mover)'
    lore:
      - 'Recoge este soporte de armadura para moverlo.'
  gui_clone:
    name: 'Clonar'
    lore:
      - 'Clona este soporte de armadura y recógelo.'
  gui_gen_cmd:
    name: 'Generar comando de invocación'
    lore:
      - 'Se creará un bloque de comando'
      - 'Se registrará el comando de invocación'
  gui_invis:
    name: 'Alternar visibilidad'
    lore:
  gui_size:
    name: 'Alternar tamaño'
    lore:
  gui_base:
    name: 'Alternar base'
    lore:
  gui_grav:
    name: 'Alternar gravedad'
    lore:
  gui_arms:
    name: 'Alternar brazos'
    lore:
  gui_name:
    name: 'Cambiar nombre'
    lore:
  gui_slots:
    name: 'Alternar bloqueo de equipo'
    lore:
  gui_pHead:
    name: 'Dar cabeza de jugador'
    lore:
  gui_invul:
    name: 'Alternar invulnerabilidad'
    lore:
  gui_glow:
    name: 'Alternar brillo'
    lore:
  gui_head:
    name: 'Mover cabeza'
    lore:
      - 'Cambiar la posición de la cabeza'
  gui_body:
    name: 'Mover cuerpo'
    lore:
      - 'Cambiar la posición del cuerpo'
  gui_larm:
    name: 'Mover brazo izquierdo'
    lore:
      - 'Cambiar la posición del brazo izquierdo'
  gui_rarm:
    name: 'Mover brazo derecho'
    lore:
      - 'Cambiar la posición del brazo derecho'
  gui_lleg:
    name: 'Mover pierna izquierda'
    lore:
      - 'Cambiar la posición de la pierna izquierda'
  gui_rleg:
    name: 'Mover pierna derecha'
    lore:
      - 'Cambiar la posición de la pierna derecha'
  gui_item:
    name: 'Recoger como artículo'
    lore:
      - 'Crea un elemento de soporte de armadura para este soporte de armadura'
      - 'Modo creativo: el soporte de la armadura permanece'
      - 'Modo de supervivencia: se elimina el soporte de armadura'

**Comment by St3venAU** [comment]
Thanks for doing this translation. I have added it to the list on the spigot resource page.
